config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]
  # get /flats
  def index
    @flats = Flat.all
  end

  # get /flats/:id
  def show
  end

  # get /flats/new
  def new
    @flat = Flat.new
  end

  def edit
  end

  # post /flats
  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: "flat was successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # patch /flats/:id
  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: "Flat was successfully updated!"
    else
      render :edit, status: :unproccessable_entity
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence %>

<div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.submit %>
  </div>
<% end %>

app/views/flats/index.html.erb
<nav class="navbar bg-body-tertiary" style="background-color: #f8f9fa;">
  <div class="container-fluid">
  <p class="mb-0">Simple Airbnb</p>
  <button type="button" class="btn btn-outline-primary"><%= link_to 'Add Flat', new_flat_path %></button>
  </div></nav>

<div class="container">
<h1 class="mx-4 mt-3">All our flats (<%= @flats.count %>)</h1>
<div class="container d-flex mt-3">
  <% @flats.each do |flat| %>
  <%= render flat %>
  <% end %>
</div>
</div>
</div>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
<%= link_to 'Back to flats', flats_path %>
</div>

app/views/flats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flat %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>